# Generated by Django 3.1.7 on 2021-03-31 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
